demandantes_index:
    path:     /
    defaults: { _controller: "AppBundle:Demandantes:index" }
    methods:  GET

demandantes_show:
    path:     /{idDemandante}/show
    defaults: { _controller: "AppBundle:Demandantes:show" }
    methods:  GET

demandantes_new:
    path:     /new
    defaults: { _controller: "AppBundle:Demandantes:new" }
    methods:  [GET, POST]

demandantes_edit:
    path:     /{idDemandante}/edit
    defaults: { _controller: "AppBundle:Demandantes:edit" }
    methods:  [GET, POST]

demandantes_delete:
    path:     /{idDemandante}/delete
    defaults: { _controller: "AppBundle:Demandantes:delete" }
    methods:  DELETE
