departamentos_index:
    path:     /
    defaults: { _controller: "AppBundle:Departamentos:index" }
    methods:  GET

departamentos_show:
    path:     /{idDepartamento}/show
    defaults: { _controller: "AppBundle:Departamentos:show" }
    methods:  GET

departamentos_new:
    path:     /new
    defaults: { _controller: "AppBundle:Departamentos:new" }
    methods:  [GET, POST]

departamentos_edit:
    path:     /{idDepartamento}/edit
    defaults: { _controller: "AppBundle:Departamentos:edit" }
    methods:  [GET, POST]

departamentos_delete:
    path:     /{idDepartamento}/delete
    defaults: { _controller: "AppBundle:Departamentos:delete" }
    methods:  DELETE
