estadosciviles_index:
    path:     /
    defaults: { _controller: "AppBundle:Estadosciviles:index" }
    methods:  GET

estadosciviles_show:
    path:     /{idEstadocivil}/show
    defaults: { _controller: "AppBundle:Estadosciviles:show" }
    methods:  GET

estadosciviles_new:
    path:     /new
    defaults: { _controller: "AppBundle:Estadosciviles:new" }
    methods:  [GET, POST]

estadosciviles_edit:
    path:     /{idEstadocivil}/edit
    defaults: { _controller: "AppBundle:Estadosciviles:edit" }
    methods:  [GET, POST]

estadosciviles_delete:
    path:     /{idEstadocivil}/delete
    defaults: { _controller: "AppBundle:Estadosciviles:delete" }
    methods:  DELETE
