laborales_index:
    path:     /
    defaults: { _controller: "AppBundle:Laborales:index" }
    methods:  GET

laborales_show:
    path:     /{idTipolaboral}/show
    defaults: { _controller: "AppBundle:Laborales:show" }
    methods:  GET

laborales_new:
    path:     /new
    defaults: { _controller: "AppBundle:Laborales:new" }
    methods:  [GET, POST]

laborales_edit:
    path:     /{idTipolaboral}/edit
    defaults: { _controller: "AppBundle:Laborales:edit" }
    methods:  [GET, POST]

laborales_delete:
    path:     /{idTipolaboral}/delete
    defaults: { _controller: "AppBundle:Laborales:delete" }
    methods:  DELETE
