AppBundle\Entity\Demandados:
    type: entity
    table: demandados
    id:
        idDemandado:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: Id_Demandado
            generator:
                strategy: IDENTITY
    fields:
        nombreDemandado:
            type: string
            nullable: false
            length: 75
            options:
                fixed: false
            column: Nombre_Demandado
        direccionDemandado:
            type: string
            nullable: false
            length: 200
            options:
                fixed: false
            column: Direccion_Demandado
        dirnotificacionDemandado:
            type: string
            nullable: true
            length: 200
            options:
                fixed: false
            column: DirNotificacion_Demandado
        telefonoDemandado:
            type: bigint
            nullable: false
            options:
                unsigned: false
            column: Telefono_Demandado
    lifecycleCallbacks: {  }
